add SonarCloud in pipeline

diff --git a/.github/workflows/ci-cd-pipeline.yml b/.github/workflows/ci-cd-pipeline.yml
--- a/.github/workflows/ci-cd-pipeline.yml
+++ b/.github/workflows/ci-cd-pipeline.yml
@@ -58,6 +58,36 @@ jobs:
         run: echo "Pipeline stopped due to coverage under 80%"
         continue-on-error: false
 
+      # analyse du code avec SonarCloud
+      - name: SonarCloud Scan
+        uses: sonarsource/sonarcloud-github-action@v3.0.0
+        with:
+          args: >
+            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
+            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
+            -Dsonar.python.coverage.reportPaths=coverage.xml
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+
+      # on vérifie si le niveau de qualité est atteint (reponse de l'API SonarCloud)
+      - name: Check SonarCloud Quality Gate
+        run: |
+          echo "Checking status..."
+          RESPONSE=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" \
+            "https://sonarcloud.io/api/qualitygates/project_status?projectKey=${{ secrets.SONAR_PROJECT_KEY }}")
+
+          echo "SonarCloud response: $RESPONSE"
+          
+          STATUS=$(echo $RESPONSE | jq -r '.projectStatus.status')
+          if [ "$STATUS" != "OK" ]; then
+            echo "Quality Gate failed: $STATUS"
+            exit 1
+          else
+            echo "Quality Gate passed!"
+          fi
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+
       # Generation de la doc avec Sphinx
       - name: Build Documentation with Sphinx
         env:
